trigger:
- develop

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm run security:audit
  displayName: 'Run npm dependancy security audit'

- script: |
    npm run test:unit
  displayName: 'Run unit test'